text(Welcome to the SimpleScript home page. There are a bunch of tools to use and you can download this open source software.)
button(How to Use This Language=Simple-Script.github.io/documentation/)
button(Download=Simple-Script.github.io/download/)
button(Patch Notes=Simple-Script.github.io/patch/)
button(Help=Simple-Script.github.io/help/)
button(Brainfu*k=Simple-Script.github.io/bf/)
button(GitHub Code=github.com/Kellarosaa/SimpleScript.git)
