text(Welcome to the SimpleScript home page. There are a bunch of tools to use and you can download this open source software.)
button(Download=kellarosaa.github.io/SimpleScript/download/)
button(Patch Notes=kellarosaa.github.io/SimpleScript/patch/)
button(Help=kellarosaa.github.io/SimpleScript/help/)
button(GitHub Code=github.com/Kellarosaa/SimpleScript.git)
