text(This is documentation on how to use this code language)
text(Step-1-set up your repo/code.)
text(To do this you can go to downloads then download the newest version. Then go to the .ss file maker and input your ss code url for example, raw.githubusercontent.com and it gives you the file.)
text(Then download the compiler, zip or exe it doesn't matter then run the exe as admininistrator, if you don't want to run it as admin download the zip or look through the "ss-compiler.py" in the repo. Then open the "output.ss" file using the tool. now you can run your code and it can be edited from the repo or where your code url is stored.)
text(Step-2-How to Code)
text(Making text-type the "text()" command and put your text inside of the parentheses to display it on your site.)
text(Hyperlinks-type https:// then your link to create a blue hyperlink.)
text(button links-button(example=example.com)
